version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: guest-post-order-flow-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guest_post_order_flow
    volumes:
      - ./database_backup:/backup
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: