version: '3.8'

services:
  postgres-test:
    image: postgres:17-alpine
    container_name: guest-post-test-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword123
      POSTGRES_DB: guest_post_test
    volumes:
      - ./database_backup:/backup
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data: