'use client';

import React from 'react';
import { WorkflowStep, GuestPostWorkflow } from '@/types/workflow';
import { SavedField } from '../SavedField';
import { ExternalLink } from 'lucide-react';

interface KeywordResearchStepProps {
  step: WorkflowStep;
  workflow: GuestPostWorkflow;
  onChange: (data: any) => void;
}

export const KeywordResearchStep = ({ step, workflow, onChange }: KeywordResearchStepProps) => {
  return (
    <div className="space-y-4">
      <div className="bg-blue-50 p-4 rounded-md">
        <h3 className="font-semibold mb-2">Step 2a: Find Topically Relevant Keywords</h3>
        <p className="text-sm mb-2">
          Take your client URL <span className="font-semibold text-blue-700">({workflow.clientUrl})</span> and paste it into this GPT to get a list of keywords:
        </p>
        <a href="https://chatgpt.com/g/g-685ea890d99c8191bd1550784c329f03-find-topically-relevant-keywords-your-client-page?model=o3" 
           target="_blank" 
           className="text-blue-600 hover:underline inline-flex items-center font-medium">
          Find Topically Relevant Keywords GPT <ExternalLink className="w-3 h-3 ml-1" />
        </a>
      </div>
      
      <SavedField
        label="Keywords from GPT (Step 2a Output)"
        value={step.outputs.keywords || ''}
        placeholder="Paste the list of keywords generated by ChatGPT"
        onChange={(value) => onChange({ ...step.outputs, keywords: value })}
        isTextarea={true}
      />

      <div className="bg-blue-50 p-4 rounded-md">
        <h3 className="font-semibold mb-2">Step 2b: Validate Keywords in Ahrefs</h3>
        <p className="text-sm mb-2">
          Take the keyword list from Step 2a and go to this Ahrefs URL:
        </p>
        <a href="https://app.ahrefs.com/v2-site-explorer/organic-keywords?brandedMode=all&chartGranularity=daily&chartInterval=year5&compareDate=dontCompare&country=us&currentDate=today&dataMode=text&hiddenColumns=&intentsAttrs=&keywordRules=%5B%5B%22contains%22%2C%22all%22%5D%2C%22compliance%2C%20regulatory%2C%20grc%2C%20risk%20management%2C%20risk%2C%20certification%2C%20security%22%2C%22any%22%5D&limit=100&localMode=all&mainOnly=0&mode=subdomains&multipleUrlsOnly=0&offset=0&performanceChartTopPosition=top11_20%7C%7Ctop21_50%7C%7Ctop3%7C%7Ctop4_10%7C%7Ctop51&positionChanges=&serpFeatures=&sort=OrganicTrafficInitial&sortDirection=desc&target=https%3A%2F%2Fm2sys.com%2F&urlRules=&volume_type=average" 
           target="_blank" 
           className="text-blue-600 hover:underline inline-flex items-center font-medium break-all">
          Ahrefs Site Explorer - Organic Keywords <ExternalLink className="w-3 h-3 ml-1 flex-shrink-0" />
        </a>
        <p className="text-sm mt-3 mb-2 font-semibold">Then:</p>
        <ol className="text-sm space-y-1 ml-4">
          <li>1. <strong>Replace keywords</strong> in the URL filter with keywords from ChatGPT output</li>
          <li>2. <strong>Change the domain</strong> in search bar to <span className="font-semibold text-blue-700">{workflow.targetDomain}</span></li>
          <li>3. <strong>Export to CSV</strong> if the site has relevant results</li>
          <li>4. <strong>If no results</strong> → this site is not viable</li>
        </ol>
      </div>

      <div>
        <label className="block text-sm font-medium mb-1">Ahrefs CSV Export Status</label>
        <select
          value={step.outputs.csvExported || ''}
          onChange={(e) => onChange({ ...step.outputs, csvExported: e.target.value })}
          className="w-full px-3 py-2 border rounded-md"
        >
          <option value="">Select status...</option>
          <option value="exported">CSV Exported - Site has relevant results</option>
          <option value="not-viable">No results - Site not viable</option>
        </select>
      </div>

      <div className="bg-blue-50 p-4 rounded-md">
        <h3 className="font-semibold mb-2">Step 2c: Get Client URL Summaries</h3>
        <p className="text-sm mb-2">
          Input the client URL(s) you want to write a guest post for. <br/>
          <strong>Your client URL:</strong> <span className="text-blue-700">{workflow.clientUrl}</span>
        </p>
        <a href="https://chatgpt.com/g/g-685eb391880c8191afc2808e42086ade-summarize-the-client-s-articles-or-urls?model=o3" 
           target="_blank" 
           className="text-blue-600 hover:underline inline-flex items-center font-medium">
          Summarize Client URLs GPT <ExternalLink className="w-3 h-3 ml-1" />
        </a>
        <p className="text-sm mt-2 italic">
          Tip: You can add multiple URLs if unsure which would be most relevant
        </p>
      </div>

      <SavedField
        label="Client URL(s) Used"
        value={step.outputs.clientUrls || ''}
        placeholder="List the client URLs you submitted to the GPT"
        onChange={(value) => onChange({ ...step.outputs, clientUrls: value })}
        isTextarea={true}
        height="h-20"
      />

      <SavedField
        label="URL Summaries Output (Step 2c)"
        value={step.outputs.urlSummaries || ''}
        placeholder="Paste the output with target URLs and summaries"
        onChange={(value) => onChange({ ...step.outputs, urlSummaries: value })}
        isTextarea={true}
      />
    </div>
  );
};